import { Video, LearningPath, Channel } from "@/types";

export const mockChannels: Channel[] = [
  {
    id: "1",
    name: "Neural Academy",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=neural",
    subscribers: 245000,
    verified: true,
  },
  {
    id: "2",
    name: "Design Clarity",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=design",
    subscribers: 128000,
    verified: true,
  },
  {
    id: "3",
    name: "Code Forge",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=code",
    subscribers: 89000,
  },
  {
    id: "4",
    name: "Science Depth",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=science",
    subscribers: 312000,
    verified: true,
  },
];

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "Как работают трансформеры: полное объяснение с нуля",
    description: "Разбираем архитектуру Transformer от Attention до Decoder. Без воды, только суть.",
    thumbnail: "https://picsum.photos/seed/transformers/640/360",
    duration: 1842,
    views: 128400,
    createdAt: "2026-09-10T10:00:00Z",
    channel: mockChannels[0],
    tags: ["AI", "Machine Learning", "Transformers"],
    summary: "Трансформеры — основа современных LLM. В этом видео разбираем механизм внимания, позиционные кодировки и почему эта архитектура победила RNN.",
    chapters: [
      { title: "Введение", timestamp: 0 },
      { title: "Self-Attention", timestamp: 180 },
      { title: "Multi-Head Attention", timestamp: 420 },
      { title: "Позиционные кодировки", timestamp: 780 },
      { title: "Encoder-Decoder", timestamp: 1100 },
      { title: "Практика", timestamp: 1500 },
    ],
  },
  {
    id: "2",
    title: "Системный дизайн интерфейсов: от хаоса к ясности",
    description: "Как создавать интерфейсы, которые не перегружают пользователя.",
    thumbnail: "https://picsum.photos/seed/design/640/360",
    duration: 1320,
    views: 45600,
    createdAt: "2026-09-12T14:30:00Z",
    channel: mockChannels[1],
    tags: ["Design", "UI/UX", "Product"],
    summary: "Практический подход к созданию чистых и понятных интерфейсов. Иерархия, воздух, типографика и визуальный вес.",
  },
  {
    id: "3",
    title: "TypeScript на продвинутом уровне: дженерики и условные типы",
    description: "Глубокое погружение в систему типов TypeScript.",
    thumbnail: "https://picsum.photos/seed/typescript/640/360",
    duration: 2100,
    views: 78200,
    createdAt: "2026-09-08T09:15:00Z",
    channel: mockChannels[2],
    tags: ["TypeScript", "Programming", "Frontend"],
  },
  {
    id: "4",
    title: "Квантовая механика без формул: интуитивное понимание",
    description: "Объясняем странности квантового мира простым языком.",
    thumbnail: "https://picsum.photos/seed/quantum/640/360",
    duration: 1680,
    views: 203000,
    createdAt: "2026-09-05T16:00:00Z",
    channel: mockChannels[3],
    tags: ["Physics", "Science", "Quantum"],
    summary: "Суперпозиция, запутанность и принцип неопределённости — разбираем без сложной математики, но с правильной интуицией.",
  },
  {
    id: "5",
    title: "Next.js 15: App Router, Server Components и производительность",
    description: "Всё, что нужно знать о современном Next.js.",
    thumbnail: "https://picsum.photos/seed/nextjs/640/360",
    duration: 1950,
    views: 95400,
    createdAt: "2026-09-14T11:20:00Z",
    channel: mockChannels[2],
    tags: ["Next.js", "React", "Web Development"],
  },
  {
    id: "6",
    title: "Как учиться эффективно: наука о памяти и внимании",
    description: "Методы, которые реально работают, основанные на исследованиях.",
    thumbnail: "https://picsum.photos/seed/learning/640/360",
    duration: 1440,
    views: 167800,
    createdAt: "2026-09-11T08:45:00Z",
    channel: mockChannels[0],
    tags: ["Learning", "Productivity", "Science"],
  },
  {
    id: "7",
    title: "Figma для продуктовых дизайнеров: продвинутые техники",
    description: "Auto Layout, Variables, Components и система дизайна.",
    thumbnail: "https://picsum.photos/seed/figma/640/360",
    duration: 1560,
    views: 52300,
    createdAt: "2026-09-13T13:00:00Z",
    channel: mockChannels[1],
    tags: ["Figma", "Design", "UI"],
  },
  {
    id: "8",
    title: "Нейросети с нуля: от перцептрона до современных архитектур",
    description: "Полный путь понимания нейронных сетей.",
    thumbnail: "https://picsum.photos/seed/neural/640/360",
    duration: 2400,
    views: 189200,
    createdAt: "2026-09-07T10:30:00Z",
    channel: mockChannels[0],
    tags: ["AI", "Deep Learning", "Neural Networks"],
  },
];

export const mockLearningPaths: LearningPath[] = [
  {
    id: "1",
    title: "Основы машинного обучения",
    description: "От линейной регрессии до нейросетей. Структурированный путь.",
    thumbnail: "https://picsum.photos/seed/ml-path/640/360",
    videosCount: 12,
    progress: 35,
    category: "AI & ML",
  },
  {
    id: "2",
    title: "Современный Frontend 2026",
    description: "React, Next.js, TypeScript и лучшие практики.",
    thumbnail: "https://picsum.photos/seed/frontend-path/640/360",
    videosCount: 18,
    progress: 60,
    category: "Development",
  },
  {
    id: "3",
    title: "Дизайн-мышление и UI/UX",
    description: "Как создавать продукты, которые любят пользователи.",
    thumbnail: "https://picsum.photos/seed/ux-path/640/360",
    videosCount: 9,
    progress: 10,
    category: "Design",
  },
  {
    id: "4",
    title: "Физика для любознательных",
    description: "От классики до квантовой механики — интуитивно.",
    thumbnail: "https://picsum.photos/seed/physics-path/640/360",
    videosCount: 15,
    category: "Science",
  },
];
